export const ROUTES = {
  HOME: "/",
  ABOUT: "/about",
  SIGN_UP: "/signup",
  SIGN_IN: "/signin",
  FORGOT_PASSWORD: "/forgotpassword",
  ACCOUNT: "/dashboard/account",
  DASHBOARD: "/dashboard",
  SUBSCRIPTIONS: "/dashboard/subscriptions",
  SUBSCRIBE: "/dashboard/subscribe/:id",
  PAYMENT_METHODS: "/dashboard/payment-methods",
  NEW_PAYMENT_METHOD: "/dashboard/payment-methods/new",
  ADMIN: "/admin",
  PLANS: "/admin/plans",
  PLAN: "/admin/plans/:id",
  NEW_PLAN: "/admin/plans/new",
  NOT_ALLOWED: "/notallowed",
  NO_MATCH: "*",
  MAP: "/map",
  SICK: "/sick",
  REPORT: "/report/:token/:record_id",
  HOSPITAL: "/hospital",
  STAFFS: "/hospital/staff",
  SCHEDULE: "/hospital/schedule",
  PATIENTS: "/hospital/patients",
  PUBLIC: "/hospital/public"
};
